2021-02-18 21:49:47.137256: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2021-02-18 21:49:47.137627: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2021-02-18 21:49:47.137646: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2021-02-18 21:49:50.035593: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-02-18 21:49:50.035742: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2021-02-18 21:49:50.035783: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c322.oscer.ou.edu): /proc/driver/nvidia/version does not exist
2021-02-18 21:49:50.036016: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-02-18 21:49:50.045474: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300140000 Hz
2021-02-18 21:49:50.047370: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x51c1430 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-02-18 21:49:50.047392: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "xor_base.py", line 150, in <module>
    execute_exp(args)
  File "xor_base.py", line 82, in execute_exp
    np.savetxt('predictions_{}'.format(args.exp),predictions,delimeter=',')
  File "<__array_function__ internals>", line 4, in savetxt
TypeError: _savetxt_dispatcher() got an unexpected keyword argument 'delimeter'
